### ISSUE TITLE
inconsistent use of tabs and spcaes in indentation

### ISSUE THREAD

**Issue by cjekel** [alexblaessle/constrNMPy#3]
Python 3 won't let you mix tabs or spaces.

You really should just use spaces -- but this is always a big debate...

I'm going to see if I can get this working, and then I'll send a PR.

I'm excited to try this library on my problem, so thank you very much for the implementation!

**Comment by alexblaessle** [comment]
Hey,

thanks for bringing that up. I normally use tabs, but apparently this time I was inconsistent. I have been traveling lately and was without internet for a while.  Did you figure it out and was my toolbox helpful?

**Comment by cjekel** [comment]
I found the toolbox helpful and was able to fix the tabs/spaces inconsistency with Python 3. 

My PR ( https://github.com/alexblaessle/constrNMPy/pull/4 ) sets all of the spaces to tabs, and it's been the version I'm using.

Thanks!

*EDIT: add link to PR

**Comment by alexblaessle** [comment]
Sweet, I merged it. Thanks! I'll close this issue now.
