### ISSUE TITLE
Inequality transitivity constraints

### ISSUE THREAD

**Issue by Goschjann** [alexblaessle/constrNMPy#5]
Hi, 

I am tuning thresholds for a ML Algorithm to backmap regression scores to ordinal classes. 

Constrained optimization is necessary as I want to enforce an ordinal structure amongst them (cut1 < cut2 ... < cut8)

Thus, I would like to use your constrained NM implementation, but:
* as far as I get it, I can only set fixed upper/ lower bounds for the single thresholds (variables)
* unftly, they depend on each other

Did I miss sth here? 

Thx a lot in advance guys!

**Comment by alexblaessle** [comment]
Hi,

glad you found my toolbox. About your questions:

- You can set for each variable a tuple of lower/upper bounds. 
- My toolbox cannot do bounds that depend on each other yet. Can you transform your problem such that you have fixed boundaries and then apply the NM algorithm?

**Comment by Goschjann** [comment]
Hi Alex, 

thanks for your good work and your answer! Unfortunately I cannot transform the problem that way but I figured out a (quite hacky but still working) solution with scikits fmin() function!

Cheers!

**Comment by alexblaessle** [comment]
Issue closed since this is more a request for a feature that is somewhat unfeasible (at least for now).
